import { ToolCategory, ToolItem, BlogPost } from '../types';

export const CATEGORY_INFO: Record<ToolCategory, { name: string; description: string; icon: string }> = {
  'pdf-tools': {
    name: 'PDF Tools',
    description: 'Merge, split, compress, rotate, protect, sign, and manage PDF documents directly in your browser.',
    icon: 'FileText',
  },
  'ai-pdf-tools': {
    name: 'AI PDF Tools',
    description: 'Chat with documents, extract key takeaways, generate quizzes, flashcards, and analyze complex reports.',
    icon: 'Sparkles',
  },
  'ocr-tools': {
    name: 'OCR Tools',
    description: 'Convert scanned PDFs, images, receipts, and invoices into searchable text and tabular spreadsheets.',
    icon: 'ScanText',
  },
  'document-tools': {
    name: 'Document Converters',
    description: 'Convert between Word, Excel, PowerPoint, Text, HTML, and CSV with high fidelity.',
    icon: 'FileSpreadsheet',
  },
  'ai-writing-tools': {
    name: 'AI Writing Suite',
    description: 'Draft emails, polish essays, optimize resumes, generate cover letters, and proofread grammar.',
    icon: 'PenTool',
  },
  'education-tools': {
    name: 'Student & Study AI',
    description: 'Interactive study guides, flashcard decks, homework explanations, and citation generators.',
    icon: 'GraduationCap',
  },
  'business-tools': {
    name: 'Business & Finance AI',
    description: 'Extract invoice line items, summarize commercial contracts, analyze balance sheets, and draft proposals.',
    icon: 'Briefcase',
  },
  'image-tools': {
    name: 'Image & File Utilities',
    description: 'Compress, resize, convert screenshots to text, and bundle photos into clean PDFs.',
    icon: 'Image',
  },
};

export const ALL_TOOLS: ToolItem[] = [
  // --- 1. PDF TOOLS ---
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    category: 'pdf-tools',
    shortDesc: 'Combine multiple PDF files into one unified document with custom page ordering.',
    badge: 'Popular',
    icon: 'Layers',
    seoTitle: 'Merge PDF Online – Combine Multiple PDFs Free | DocuNova AI',
    metaDesc: 'Merge PDF files online in seconds with DocuNova AI. Combine multiple documents into one clean PDF with custom page ordering, zero server storage, and complete privacy.',
    h1: 'Merge Multiple PDF Files Online',
    howToSteps: [
      'Upload two or more PDF files using the dropzone or file picker.',
      'Drag and drop files to arrange them in your desired sequence.',
      'Click "Merge PDFs" to combine documents locally in your browser.',
      'Download your merged PDF file instantly.',
    ],
    features: [
      'Client-side zero-latency processing',
      'Unlimited file merging with custom reordering',
      'Preserves original bookmark structures and links',
      'Zero server upload for total data privacy',
    ],
    faqs: [
      {
        question: 'Is there a limit on how many PDFs I can merge?',
        answer: 'DocuNova AI allows merging as many PDF files as your device memory permits, directly in your browser without throttling.',
      },
      {
        question: 'Are my merged documents stored on your servers?',
        answer: 'No. Merge operations run client-side using WebAssembly PDF engines. Your documents never leave your computer.',
      },
    ],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    name: 'Split PDF',
    category: 'pdf-tools',
    shortDesc: 'Extract individual pages or custom page ranges into separate downloadable PDFs.',
    badge: 'Popular',
    icon: 'Scissors',
    seoTitle: 'Split PDF Online – Extract Pages from PDF | DocuNova AI',
    metaDesc: 'Split PDF pages into standalone documents easily. Select custom page ranges or extract all pages individually with instant client-side processing.',
    h1: 'Split PDF Pages Instantly',
    howToSteps: [
      'Select and upload the PDF file you wish to split.',
      'Enter the target page ranges (e.g. 1-3, 5, 8-10) or choose individual extraction.',
      'Click "Split PDF" to process pages.',
      'Download your extracted PDF files immediately.',
    ],
    features: [
      'Extract custom page ranges or single pages',
      'Instant thumbnail preview of every page',
      'Preserves vector fonts and high-resolution images',
    ],
    faqs: [
      {
        question: 'How do I specify multiple page ranges?',
        answer: 'You can enter comma-separated numbers and hyphenated ranges such as "1-4, 7, 9-12".',
      },
    ],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    category: 'pdf-tools',
    shortDesc: 'Reduce PDF file size significantly while retaining crisp text and image clarity.',
    badge: 'Popular',
    icon: 'Minimize2',
    seoTitle: 'Compress PDF Online – Reduce PDF File Size | DocuNova AI',
    metaDesc: 'Reduce PDF file sizes by up to 80% without losing readable quality. Fast, secure, and perfect for email attachments and portal uploads.',
    h1: 'Compress PDF File Size Online',
    howToSteps: [
      'Upload your heavy PDF document.',
      'Select compression level: Extreme, Recommended, or High Quality.',
      'Click "Compress PDF" to optimize font tables and embedded bitmaps.',
      'Download the slimmed-down PDF file.',
    ],
    features: [
      'Intelligent image downscaling and font subsetting',
      'Up to 85% file size reduction',
      'Side-by-side before/after file size comparison',
    ],
    faqs: [
      {
        question: 'Will compression blur my text?',
        answer: 'No. Vector text glyphs and outlines remain sharp and vector-based at all compression levels.',
      },
    ],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'pdf-tools',
    shortDesc: 'Permanently rotate upside-down or sideways pages clockwise or counter-clockwise.',
    icon: 'RotateCw',
    seoTitle: 'Rotate PDF Pages Online Free – DocuNova AI',
    metaDesc: 'Rotate PDF pages 90, 180, or 270 degrees. Fix scanned page orientation permanently with instant browser-based processing.',
    h1: 'Rotate PDF Pages Permanently',
    howToSteps: [
      'Upload your PDF file.',
      'Choose whether to rotate all pages or specific page numbers.',
      'Select 90°, 180°, or 270° clockwise rotation.',
      'Click "Apply Rotation" and download.',
    ],
    features: ['Rotate individual or all pages', 'Instant visual verification', 'Lossless page rotation'],
    faqs: [{ question: 'Does rotating alter the PDF text content?', answer: 'No, page coordinates are updated losslessly without re-encoding text.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'delete-pdf-pages',
    slug: 'delete-pdf-pages',
    name: 'Delete PDF Pages',
    category: 'pdf-tools',
    shortDesc: 'Remove unwanted, blank, or sensitive pages from any PDF document effortlessly.',
    icon: 'Trash2',
    seoTitle: 'Delete Pages from PDF Online | DocuNova AI',
    metaDesc: 'Remove blank or unnecessary pages from your PDF documents in seconds. Secure, private, and free.',
    h1: 'Delete Unwanted PDF Pages',
    howToSteps: [
      'Upload the PDF file.',
      'Click the pages you wish to eliminate or specify numbers (e.g. 2, 5, 8).',
      'Click "Delete Selected Pages".',
      'Download the streamlined PDF.',
    ],
    features: ['Click-to-remove visual thumbnails', 'Range-based deletion', 'Instant file regeneration'],
    faqs: [{ question: 'Can I undo deleted pages?', answer: 'Your original file on your computer remains untouched. You can re-upload at any time.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark-pdf',
    name: 'Add Watermark to PDF',
    category: 'pdf-tools',
    shortDesc: 'Stamp custom confidential, draft, or branded text watermarks across all pages.',
    icon: 'Stamp',
    seoTitle: 'Add Watermark to PDF Online – Custom Text Stamp | DocuNova AI',
    metaDesc: 'Add confidential, copyright, or draft watermarks to any PDF document. Adjust opacity, font size, angle, and position.',
    h1: 'Stamp Watermarks on PDF Pages',
    howToSteps: [
      'Upload your PDF file.',
      'Enter your watermark text (e.g. "CONFIDENTIAL", "DRAFT", "COPYRIGHT").',
      'Adjust rotation angle, font size, and transparency slider.',
      'Click "Apply Watermark" and download.',
    ],
    features: ['Custom diagonal or horizontal placement', 'Adjustable opacity & font sizing', 'Applies across all pages uniformly'],
    faqs: [{ question: 'Can watermarks be removed easily?', answer: 'Watermarks are baked into the PDF content stream to prevent simple deletion.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'add-page-numbers',
    slug: 'add-page-numbers',
    name: 'Add Page Numbers',
    category: 'pdf-tools',
    shortDesc: 'Insert numbered pagination at the header or footer of your PDF pages.',
    icon: 'Hash',
    seoTitle: 'Add Page Numbers to PDF Online | DocuNova AI',
    metaDesc: 'Add custom page numbering (Page X of Y) to PDF headers or footers with customizable alignments and margins.',
    h1: 'Add Numbers and Pagination to PDF',
    howToSteps: ['Upload your PDF.', 'Select position (Bottom Center, Bottom Right, Top Right).', 'Choose format (e.g., "Page 1 of 10").', 'Apply and download.'],
    features: ['Multiple numbering styles', 'Header or footer position', 'Preserves margins'],
    faqs: [{ question: 'Can I skip numbering the title page?', answer: 'Yes, you can configure numbering to start on page 2 or any custom offset.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'pdf-password-protect',
    slug: 'pdf-password-protect',
    name: 'Protect PDF with Password',
    category: 'pdf-tools',
    shortDesc: 'Encrypt your document with AES standard passwords to prevent unauthorized access.',
    badge: 'New',
    icon: 'Lock',
    seoTitle: 'Password Protect PDF Online – AES Encrypt PDF | DocuNova AI',
    metaDesc: 'Encrypt sensitive documents with robust user passwords. Keep confidential financial, legal, and personal PDFs secure.',
    h1: 'Encrypt and Password Protect Your PDF',
    howToSteps: ['Upload the sensitive PDF document.', 'Enter and confirm your strong password.', 'Click "Encrypt Document".', 'Download your secure PDF.'],
    features: ['Strong document encryption', 'Password-gated viewing and printing', 'Zero server storage of passwords'],
    faqs: [{ question: 'What happens if I lose my password?', answer: 'Because DocuNova AI respects zero-knowledge security, passwords cannot be recovered if forgotten.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    name: 'Sign PDF Online',
    category: 'pdf-tools',
    shortDesc: 'Draw or stamp your legal handwritten signature directly onto PDF agreements.',
    icon: 'PenTool',
    seoTitle: 'Sign PDF Online Free – Electronic Document Signature | DocuNova AI',
    metaDesc: 'Sign PDF contracts, NDAs, and forms online. Draw with mouse/touch or type your name for an instant signature stamp.',
    h1: 'Electronically Sign PDF Documents',
    howToSteps: ['Upload your contract or form.', 'Draw your signature on the interactive canvas or type it.', 'Place and size the signature anywhere on the document.', 'Download the signed PDF.'],
    features: ['Smooth vector signature canvas', 'Draggable placement on any page', 'Export audit stamp'],
    faqs: [{ question: 'Is this legally binding?', answer: 'Electronic signatures are widely recognized under the ESIGN Act and eIDAS for standard commercial agreements.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'pdf-core',
  },

  // --- 2. AI PDF TOOLS ---
  {
    id: 'chat-with-pdf',
    slug: 'chat-with-pdf',
    name: 'Chat with PDF',
    category: 'ai-pdf-tools',
    shortDesc: 'Converse interactively with any document. Ask questions, get citations, and extract deep insights.',
    badge: 'AI Powered',
    icon: 'MessageSquare',
    seoTitle: 'Chat with PDF – AI Document Q&A with Citations | DocuNova AI',
    metaDesc: 'Chat directly with your PDF documents using Gemini 3 Flash. Get grounded, truthful answers with direct page citations and zero hallucinations.',
    h1: 'Intelligent Conversational Document AI',
    howToSteps: [
      'Upload any PDF, report, research paper, or textbook.',
      'Review the extracted document preview in the left pane.',
      'Type your question or choose one of the suggested prompt chips.',
      'Receive instant, grounded answers with clickable source citations.',
    ],
    features: [
      'Powered by Gemini 3 Flash intelligence',
      'Page-referenced source attribution tags',
      'Strict anti-hallucination document grounding',
      'Export chat transcripts to Markdown or PDF',
    ],
    faqs: [
      {
        question: 'Does the AI read my entire multi-page document?',
        answer: 'Yes. The engine parses the full document text, contextualizing questions against all relevant sections.',
      },
      {
        question: 'Are my proprietary documents trained into AI models?',
        answer: 'No. API queries are stateless and ephemeral; documents are never used for model re-training.',
      },
    ],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-chat',
  },
  {
    id: 'ai-pdf-summarizer',
    slug: 'ai-pdf-summarizer',
    name: 'AI PDF Summarizer',
    category: 'ai-pdf-tools',
    shortDesc: 'Condense lengthy PDFs into executive summaries, bullet highlights, or simple TL;DR briefs.',
    badge: 'Popular',
    icon: 'FileText',
    seoTitle: 'AI PDF Summarizer – Instant Executive Document Summary | DocuNova AI',
    metaDesc: 'Summarize long research papers, whitepapers, and legal agreements in seconds with AI. Choose from executive, TL;DR, or bullet breakdown modes.',
    h1: 'Summarize Long PDF Documents with AI',
    howToSteps: [
      'Upload your document or paste text.',
      'Select summary mode: Executive Summary, TL;DR, or Bullet Takeaways.',
      'Click "Generate Summary".',
      'Copy the output or export to a clean document.',
    ],
    features: ['Multiple summary lengths and tones', 'Key takeaway extraction', 'One-click copy and download'],
    faqs: [{ question: 'How fast is the summary?', answer: 'Most 20-page documents are analyzed and synthesized in under 5 seconds.' }],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-summary',
  },
  {
    id: 'ai-quiz-generator',
    slug: 'ai-quiz-generator',
    name: 'AI Quiz & MCQ Generator',
    category: 'ai-pdf-tools',
    shortDesc: 'Automatically generate multiple-choice quizzes and test questions from lecture notes or textbooks.',
    badge: 'AI Powered',
    icon: 'CheckCircle2',
    seoTitle: 'AI Quiz Generator from PDF – Create MCQs Online | DocuNova AI',
    metaDesc: 'Turn any PDF, textbook chapter, or study notes into interactive multiple choice quizzes with instant answer keys and explanations.',
    h1: 'Generate Interactive Quizzes from Documents',
    howToSteps: [
      'Upload your study material or lecture slides.',
      'Select desired question count and difficulty level.',
      'Click "Generate Quiz".',
      'Take the test interactively or print the quiz sheet with answers.',
    ],
    features: ['Auto-generated multiple choice questions', 'Instant answer verification with rationale', 'Exportable quiz sheets for teachers and students'],
    faqs: [{ question: 'Can I choose the difficulty level?', answer: 'Yes, you can configure Easy, Medium, or Advanced reasoning questions.' }],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-quiz',
  },
  {
    id: 'ai-flashcard-generator',
    slug: 'ai-flashcard-generator',
    name: 'AI Flashcard Generator',
    category: 'ai-pdf-tools',
    shortDesc: 'Extract key vocabulary, terms, and principles into interactive digital study flashcards.',
    badge: 'AI Powered',
    icon: 'Layers',
    seoTitle: 'AI Flashcard Generator from PDF | DocuNova AI',
    metaDesc: 'Generate interactive 3D study flashcards from textbook PDFs and lecture notes with AI. Practice spaced repetition online free.',
    h1: 'Generate Interactive Flashcards from PDF',
    howToSteps: [
      'Upload course syllabus, notes, or chapter PDF.',
      'Click "Create Flashcards".',
      'Flip cards interactively to test your recall.',
      'Export flashcard deck to CSV or study offline.',
    ],
    features: ['3D flip card animations', 'Includes helpful memory hints', 'Keyboard navigation (Space to flip, Arrows to advance)'],
    faqs: [{ question: 'Can I export cards to Anki or Quizlet?', answer: 'Yes, you can copy or export cards in standard comma-separated format.' }],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-flashcard',
  },
  {
    id: 'ai-study-guide',
    slug: 'ai-study-guide',
    name: 'AI Study Guide Generator',
    category: 'ai-pdf-tools',
    shortDesc: 'Synthesize complex textbooks and chapters into structured academic study blueprints.',
    badge: 'New',
    icon: 'BookOpen',
    seoTitle: 'AI Study Guide Generator – Comprehensive Notes from PDF | DocuNova AI',
    metaDesc: 'Turn dense PDF chapters into structured study guides complete with executive overviews, glossary terms, practice questions, and key formulas.',
    h1: 'Build Comprehensive Study Guides with AI',
    howToSteps: ['Upload syllabus or textbook chapter.', 'Specify course subject or title.', 'Click "Generate Study Blueprint".', 'Review and download study packet.'],
    features: ['Glossary definitions and formulas', 'Core thematic summaries', 'High-yield exam questions included'],
    faqs: [{ question: 'Is this suitable for university-level material?', answer: 'Yes, the AI analyzes advanced academic and technical literature with nuanced domain accuracy.' }],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-study-guide',
  },
  {
    id: 'ai-document-translator',
    slug: 'ai-document-translator',
    name: 'AI Document Translator',
    category: 'ai-pdf-tools',
    shortDesc: 'Translate documents into 50+ languages while preserving terminology and context.',
    icon: 'Languages',
    seoTitle: 'AI Document Translator – Translate PDF Online | DocuNova AI',
    metaDesc: 'Accurately translate documents across 50+ languages using neural AI that understands technical terms, idioms, and legal phrases.',
    h1: 'Translate PDF Documents Accurately',
    howToSteps: ['Upload the source document.', 'Select your target language (Spanish, French, German, Japanese, etc.).', 'Click "Translate Document".', 'Export the translated text.'],
    features: ['Preserves technical and industry vocabulary', 'Supports 50+ global languages', 'Side-by-side translation comparison'],
    faqs: [{ question: 'Does it preserve specialized terminology?', answer: 'Yes, the translation engine respects legal, medical, and engineering domain terms.' }],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-writing',
  },

  // --- 3. OCR TOOLS ---
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    name: 'OCR PDF (Searchable PDF)',
    category: 'ocr-tools',
    shortDesc: 'Convert flat, scanned, or image-only PDF documents into fully searchable and selectable text.',
    badge: 'Popular',
    icon: 'Scan',
    seoTitle: 'OCR PDF Online – Make Scanned PDF Searchable | DocuNova AI',
    metaDesc: 'Extract and search text from scanned PDF files. Convert unsearchable image scans into selectable, copyable digital text with optical character recognition.',
    h1: 'Convert Scanned PDFs to Searchable Text',
    howToSteps: ['Upload your scanned PDF document.', 'Select recognition language.', 'Click "Perform OCR".', 'Copy text or download searchable output.'],
    features: ['High-accuracy character recognition', 'Detects multi-column article layouts', 'Export to TXT, Word, or Searchable PDF'],
    faqs: [{ question: 'Can it read low-resolution scans?', answer: 'DocuNova AI includes image pre-processing (contrast boosting and deskewing) to read difficult scans.' }],
    acceptedMimeTypes: ['application/pdf', 'image/png', 'image/jpeg'],
    workspaceType: 'ocr',
  },
  {
    id: 'image-to-text',
    slug: 'image-to-text',
    name: 'Image to Text OCR',
    category: 'ocr-tools',
    shortDesc: 'Extract text effortlessly from photos, screenshots, receipts, and book captures.',
    icon: 'Image',
    seoTitle: 'Image to Text Converter – Online OCR | DocuNova AI',
    metaDesc: 'Extract text from JPG, PNG, WEBP, and screenshots instantly. Copy text from images with optical character recognition.',
    h1: 'Extract Text from Images and Screenshots',
    howToSteps: ['Upload or paste a screenshot/image.', 'Click "Extract Text".', 'View and edit the recognized text.', 'Copy to clipboard or download.'],
    features: ['Paste screenshot from clipboard (Ctrl+V)', 'Instant recognition in seconds', 'Preserves paragraph breaks'],
    faqs: [{ question: 'Can I paste an image directly?', answer: 'Yes, simply press Ctrl+V / Cmd+V on the workspace page to paste your clipboard image.' }],
    acceptedMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
    workspaceType: 'ocr',
  },
  {
    id: 'invoice-ocr',
    slug: 'invoice-ocr',
    name: 'Invoice & Receipt OCR',
    category: 'ocr-tools',
    shortDesc: 'Intelligently parse vendor details, line items, taxes, totals, and due dates into structured JSON/Excel.',
    badge: 'AI Powered',
    icon: 'Receipt',
    seoTitle: 'Invoice OCR & Receipt Scanner – Extract Data to Excel | DocuNova AI',
    metaDesc: 'Automate accounts payable data entry. Extract invoice numbers, dates, line items, taxes, and totals from invoices and receipts into Excel and JSON.',
    h1: 'Automate Invoice and Receipt Data Extraction',
    howToSteps: ['Upload an invoice or receipt image/PDF.', 'Click "Extract Structured Data".', 'Review detected merchant, line items, and totals.', 'Export to Excel, CSV, or JSON.'],
    features: ['Detects itemized line tables', 'Calculates tax & discount verification', 'Direct CSV and JSON export'],
    faqs: [{ question: 'Does it support international currency symbols?', answer: 'Yes, it detects USD, EUR, GBP, JPY, CAD, and various global tax formats.' }],
    acceptedMimeTypes: ['application/pdf', 'image/png', 'image/jpeg'],
    workspaceType: 'ocr',
  },
  {
    id: 'table-ocr',
    slug: 'table-ocr',
    name: 'Table OCR to Excel',
    category: 'ocr-tools',
    shortDesc: 'Detect tabular grids in images or scanned PDFs and convert them cleanly into spreadsheets.',
    icon: 'Table',
    seoTitle: 'Table OCR – Convert Images & Scanned Tables to Excel | DocuNova AI',
    metaDesc: 'Convert tables in images or scanned PDFs into editable Excel sheets. Fast optical character recognition for financial tables and spreadsheets.',
    h1: 'Convert Scanned Tables to Editable Excel',
    howToSteps: ['Upload document containing tabular data.', 'Click "Detect & Extract Tables".', 'Inspect grid preview.', 'Download as `.xlsx` or `.csv`.'],
    features: ['Grid line detection', 'Multi-column layout understanding', 'Zero manual re-typing required'],
    faqs: [{ question: 'Will merged cells be preserved?', answer: 'The engine reconstructs merged header and row relationships where possible.' }],
    acceptedMimeTypes: ['application/pdf', 'image/png', 'image/jpeg'],
    workspaceType: 'ocr',
  },

  // --- 4. DOCUMENT CONVERTERS ---
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'document-tools',
    shortDesc: 'Convert PDF files into fully editable Microsoft Word (.docx) documents.',
    badge: 'Popular',
    icon: 'FileType',
    seoTitle: 'PDF to Word Converter – Convert PDF to DOCX Free | DocuNova AI',
    metaDesc: 'Convert PDF documents into editable Microsoft Word (.docx) files. Preserve formatting, fonts, paragraphs, and tables flawlessly.',
    h1: 'Convert PDF to Editable Microsoft Word',
    howToSteps: ['Upload your PDF file.', 'Click "Convert to Word".', 'Wait for structural layout parsing.', 'Download your editable `.docx` file.'],
    features: ['Retains fonts, headings, and paragraph styling', 'Tables converted to editable Word tables', 'Fast client-assisted conversion'],
    faqs: [{ question: 'Can I edit the generated Word file in Google Docs?', answer: 'Yes, the generated `.docx` file is 100% standard and opens seamlessly in Word, Google Docs, and LibreOffice.' }],
    acceptedMimeTypes: ['application/pdf'],
    workspaceType: 'converter',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'document-tools',
    shortDesc: 'Convert Word documents (.docx, .doc) into standardized, professional PDFs.',
    icon: 'FileText',
    seoTitle: 'Word to PDF Converter – Convert DOCX to PDF Online | DocuNova AI',
    metaDesc: 'Convert DOCX documents to publication-grade PDF files. Lock in formatting, layout, and fonts across all devices.',
    h1: 'Convert Word DOCX to PDF Online',
    howToSteps: ['Upload your Word (.docx) document.', 'Click "Convert to PDF".', 'Download your standardized PDF file.'],
    features: ['Precise layout preservation', 'Fast document rendering', 'Free for daily use'],
    faqs: [{ question: 'Will my fonts change on other computers?', answer: 'No, converting to PDF embeds font definitions so the document appears identical on any device.' }],
    acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'],
    workspaceType: 'converter',
  },
  {
    id: 'text-to-pdf',
    slug: 'text-to-pdf',
    name: 'Text to PDF',
    category: 'document-tools',
    shortDesc: 'Transform plain text or Markdown notes into formatted, paginated PDF documents.',
    icon: 'AlignLeft',
    seoTitle: 'Text to PDF Converter – Create PDF from Plain Text | DocuNova AI',
    metaDesc: 'Create formatted PDF documents from plain text or Markdown. Customize font size, margins, and page layouts.',
    h1: 'Convert Plain Text to Formatted PDF',
    howToSteps: ['Paste your text into the editor or upload a .txt file.', 'Adjust title, font size, and margins.', 'Click "Generate PDF".', 'Download the formatted document.'],
    features: ['Custom typography & page margins', 'Auto-pagination', 'Instant client-side PDF creation'],
    faqs: [{ question: 'Does this require uploading my text?', answer: 'No, text-to-PDF runs entirely in your browser using client-side generators.' }],
    acceptedMimeTypes: ['text/plain'],
    workspaceType: 'converter',
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    category: 'document-tools',
    shortDesc: 'Bundle single or multiple JPG and PNG images into a clean, single PDF document.',
    badge: 'Fast',
    icon: 'Image',
    seoTitle: 'JPG to PDF Converter – Combine Images into PDF | DocuNova AI',
    metaDesc: 'Convert JPG and PNG photos into a single PDF document. Reorder images, customize page orientation and margins.',
    h1: 'Convert Images (JPG/PNG) into a PDF',
    howToSteps: ['Upload one or multiple images.', 'Drag and drop to reorder pages.', 'Click "Generate PDF Document".', 'Download your consolidated PDF.'],
    features: ['Supports multi-image merging', 'Maintains maximum image clarity', 'Client-side processing'],
    faqs: [{ question: 'Can I combine multiple pictures into one PDF?', answer: 'Yes! Select multiple photos and they will be compiled into sequential pages.' }],
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    workspaceType: 'converter',
  },

  // --- 5. AI WRITING TOOLS ---
  {
    id: 'ai-rewriter',
    slug: 'ai-rewriter',
    name: 'AI Document Rewriter & Paraphraser',
    category: 'ai-writing-tools',
    shortDesc: 'Rephrase, elevate, or adjust tone of any paragraph or document while keeping original facts.',
    badge: 'Popular',
    icon: 'RefreshCw',
    seoTitle: 'AI Rewriter & Paraphrasing Tool | DocuNova AI',
    metaDesc: 'Rewrite text with superior clarity, vocabulary, and flow. Choose from professional, academic, creative, or simplified tones.',
    h1: 'Rewrite and Paraphrase Text with AI',
    howToSteps: ['Paste your text into the left editor.', 'Choose your desired tone: Professional, Academic, Punchy, or Casual.', 'Click "Rewrite Text".', 'Compare and copy your improved draft.'],
    features: ['Multiple tone presets', 'Anti-plagiarism vocabulary variation', 'Sentence-level improvement'],
    faqs: [{ question: 'Will this change the meaning of my writing?', answer: 'No, DocuNova AI preserves your key arguments and semantic meaning.' }],
    workspaceType: 'ai-writing',
  },
  {
    id: 'ai-grammar-checker',
    slug: 'ai-grammar-checker',
    name: 'AI Grammar & Style Checker',
    category: 'ai-writing-tools',
    shortDesc: 'Deep grammar, punctuation, and structural proofreading with detailed correction rationales.',
    icon: 'CheckSquare',
    seoTitle: 'AI Grammar Checker & Proofreader Online | DocuNova AI',
    metaDesc: 'Proofread documents for grammatical, syntactic, and punctuation errors with intelligent explanations for every suggestion.',
    h1: 'Deep AI Grammar and Style Proofreader',
    howToSteps: ['Paste your text into the proofreader.', 'Click "Analyze Grammar & Style".', 'Review inline corrections and explanations.', 'Accept changes and copy.'],
    features: ['Explains WHY each correction was made', 'Checks punctuation, agreement, and style', 'High-speed analysis'],
    faqs: [{ question: 'Is this better than standard spellcheckers?', answer: 'Yes, it understands contextual nuance, passive voice, and academic cadence.' }],
    workspaceType: 'ai-writing',
  },
  {
    id: 'ai-cover-letter',
    slug: 'ai-cover-letter',
    name: 'AI Cover Letter Generator',
    category: 'ai-writing-tools',
    shortDesc: 'Create compelling, customized cover letters based on your resume and target job description.',
    icon: 'Briefcase',
    seoTitle: 'AI Cover Letter Generator – Tailored Applications | DocuNova AI',
    metaDesc: 'Generate tailored, professional cover letters that highlight your accomplishments and match job qualifications.',
    h1: 'Generate Job-Winning Cover Letters',
    howToSteps: ['Paste your candidate background or resume highlights.', 'Paste the target job description or company name.', 'Click "Generate Cover Letter".', 'Refine and copy your letter.'],
    features: ['Tailored to specific job requirements', 'Focuses on quantifiable metrics', 'Customizable tone'],
    faqs: [{ question: 'Can I tailor it to any industry?', answer: 'Yes, the AI customizes jargon and emphasis for tech, healthcare, finance, design, and more.' }],
    workspaceType: 'ai-writing',
  },

  // --- 6. STUDENT & EDUCATION AI ---
  {
    id: 'ai-homework-helper',
    slug: 'ai-homework-helper',
    name: 'AI Homework & Problem Solver',
    category: 'education-tools',
    shortDesc: 'Get step-by-step conceptual explanations for complex STEM and humanities questions.',
    badge: 'AI Powered',
    icon: 'GraduationCap',
    seoTitle: 'AI Homework Helper – Step-by-Step Explanations | DocuNova AI',
    metaDesc: 'Solve homework questions with clear, step-by-step conceptual walkthroughs. Learn the underlying principles rather than just getting answers.',
    h1: 'Step-by-Step AI Homework and Study Assistant',
    howToSteps: ['Type or paste your homework problem.', 'Provide any document context if applicable.', 'Click "Explain Step-by-Step".', 'Review detailed concepts and methodology.'],
    features: ['Step-by-step logic breakdown', 'Provides intuitive analogies', 'Encourages genuine comprehension'],
    faqs: [{ question: 'Does it explain formulas?', answer: 'Yes, it highlights every formula used and explains each variable clearly.' }],
    workspaceType: 'ai-writing',
  },

  // --- 7. BUSINESS & FINANCE AI ---
  {
    id: 'contract-summarizer',
    slug: 'contract-summarizer',
    name: 'Contract & Legal Summarizer',
    category: 'business-tools',
    shortDesc: 'Quickly spot critical clauses, liabilities, renewal deadlines, and financial obligations in agreements.',
    badge: 'New',
    icon: 'ShieldCheck',
    seoTitle: 'AI Contract Summarizer – Legal Clause Analyzer | DocuNova AI',
    metaDesc: 'Summarize commercial contracts, NDAs, and SLAs in seconds. Spot hidden liabilities, auto-renewal traps, and compliance obligations.',
    h1: 'Summarize Contracts and Identify Key Risks',
    howToSteps: ['Upload the contract or agreement (PDF/TXT).', 'Click "Analyze Agreement".', 'Review categorized risk points and obligation deadlines.', 'Export legal summary report.'],
    features: ['Flags indemnification and termination clauses', 'Extracts payment and renewal dates', 'Plain-English summary of complex legalese'],
    faqs: [{ question: 'Is this legal advice?', answer: 'DocuNova AI provides informative summaries for productivity and triage, not formal legal counsel.' }],
    acceptedMimeTypes: ['application/pdf', 'text/plain'],
    workspaceType: 'ai-summary',
  },

  // --- 8. IMAGE & FILE TOOLS ---
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    category: 'image-tools',
    shortDesc: 'Compress JPG, PNG, and WebP images up to 80% without visible quality loss.',
    icon: 'Image',
    seoTitle: 'Image Compressor Online – Compress JPG & PNG Free | DocuNova AI',
    metaDesc: 'Reduce photo and graphic image sizes online. Optimize JPG, PNG, and WebP assets for websites and emails.',
    h1: 'Compress Images Online with Zero Blur',
    howToSteps: ['Upload your image files.', 'Adjust quality slider.', 'Click "Compress".', 'Download your slimmed-down pictures.'],
    features: ['Client-side HTML5 canvas compression', 'Batch compression supported', 'Instant visual comparison'],
    faqs: [{ question: 'Are files uploaded to a server?', answer: 'No, images are compressed directly on your computer canvas.' }],
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    workspaceType: 'pdf-core',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'mastering-rag-chat-with-pdf-guide',
    title: 'The Modern Architecture of Chat-with-PDF: How RAG and Embeddings Work',
    category: 'AI & Document Tech',
    readTime: '6 min read',
    publishedAt: '2026-09-18',
    author: 'DocuNova Research Team',
    excerpt: 'Explore how Retrieval-Augmented Generation (RAG), vector embeddings, and chunking transform static PDFs into interactive, verifiable knowledge bases.',
    content: [
      'For decades, Portable Document Format (PDF) files have served as digital paper: immutable, reliable for print, yet historically stubborn to parse and interrogate dynamically.',
      'With modern LLMs and vector indexing, the paradigm has shifted. Chatting with a PDF is not merely feeding megabytes of text into a context window. Production systems employ Retrieval-Augmented Generation (RAG).',
      'First, layout parsers segment pages, headers, footers, and tables into discrete semantically contiguous chunks. Next, embedding models generate high-dimensional vectors capturing conceptual meaning.',
      'When you ask a question such as "What was the Q3 operating margin in Europe?", the system performs cosine similarity search across vector indexes, retrieving only the 3 or 4 exact paragraphs that contain the answer.',
      'Finally, an instruction-tuned model like Gemini 3 Flash synthesizes the response while attaching definitive citation footnotes (e.g. "[Page 14]"). This guarantees truthfulness and mitigates hallucinations.',
    ],
  },
  {
    slug: 'ocr-breakthroughs-for-scanned-documents',
    title: 'Next-Gen OCR: Extracting Tables and Line Items from Messy Scans',
    category: 'OCR & Vision',
    readTime: '5 min read',
    publishedAt: '2026-09-12',
    author: 'Engineering Desk',
    excerpt: 'Traditional optical character recognition often broke on multi-column layouts and skewed receipts. Discover how neural vision transformers achieve near-perfect transcription.',
    content: [
      'Anyone who has tried extracting a 20-row financial statement from a tilted photocopy knows the frustration of fragmented cells and jumbled numbers.',
      'Legacy OCR systems relied strictly on rigid bounding box algorithms. If a column separator had slight noise or an invoice lacked borders, data spilled into adjacent rows.',
      'Modern vision-language models inspect both the rasterized typography and the semantic context of labels simultaneously. They understand that a number following "VAT 20%" represents tax even if the grid line is missing.',
      'With DocuNova AI, users can convert complex physical invoices into formatted Excel spreadsheets and structured JSON in under 3 seconds.',
    ],
  },
  {
    slug: 'client-side-pdf-security-guide',
    title: 'Why Zero-Retention and Client-Side PDF Processing Matter for Enterprise Privacy',
    category: 'Privacy & Security',
    readTime: '4 min read',
    publishedAt: '2026-09-05',
    author: 'Security Architecture',
    excerpt: 'Why sending sensitive NDAs and patient medical records to third-party web converters is a severe compliance risk, and how browser WebAssembly solves it.',
    content: [
      'Every week, millions of confidential business agreements, tax filings, and personal IDs are uploaded to sketchy "free PDF tools" that store documents on unencrypted public buckets.',
      'At DocuNova AI, we designed our architecture around privacy-first engineering. Essential document operations—such as merging, rotating, splitting, deleting pages, and password protection—execute locally on your device via WebAssembly.',
      'When cloud AI intelligence is needed (such as deep document chat), sessions are ephemeral, encrypted in flight via TLS 1.3, and strictly wiped upon job completion.',
    ],
  },
];
